---
title: "R Notebook"
output: html_notebook
---

Vectores y matrices 
```{r}
estudiante1 = c(50.4, 62.3, 92.1, 77.6, TRUE)
estudiante2 = c(41.7, 87.9, 75.3, 72.4, FALSE)
estudiante3 = c(30.3, 67.8, 69.3, 71.2, FALSE)
estudiante4 = c(65.4, 85.1, 92.3, 96.8, TRUE)
estudiante5 = c(70.4, 88.2, 95.2, 90.7, TRUE)

estudiantes_vector = c(estudiante1, estudiante2, estudiante3, estudiante4, estudiante5)

estudiantes_matrix = matrix(estuadiantes_vector, byrow = TRUE, nrow = 5)
```

Nombrado de una matriz
```{r}
nombres_estudiantes = c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill")
nombres_curos_edad_legal = c("TIC", "Accounting", "Psychology", "Ethics", "Legal age")

colnames(estudiantes_matrix) = nombres_curos_edad_legal
rownames(estudiantes_matrix) = nombres_estudiantes

estudiantes_matrix
```
rowSums, cbind

```{r}
nota_total_estudiantes = rowSums(estudiantes_matrix[,1:4])
resultados_estudiantes = cbind(estudiantes_matrix, nota_total_estudiantes)
resultados_estudiantes
```

Seleccionando elementos de una matriz
```{r}
Elementos_seleccionados = resultados_estudiantes[c(1,3,5),c(2,4)]
```

Data frames

```{r}
calificaciones_estudiantes_df = data.frame(resultados_estudiantes)
subset(calificaciones_estudiantes_df, subset = Accounting > 80 & Legal.age == 1)
```

Funciones, condicionales y bucles
```{r}
proyeccion_estudiantes = function(resultados_estudiantes){
  for (row in 1:nrow(resultados_estudiantes)) {
    if (row <= 45) {
      print("Student at risk")
    }
    for (col in 1:ncol(resultados_estudiantes)) {
      
    }
    
  }
}
```
























